# Site settings
title: My Memo
email: downtorak@gmail.com
description: Memo Blog

baseurl: ""
github_username: downtorak

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
